insert into format(name, is_deleted) values('10 х 15', 'false');
insert into format(name, is_deleted) values('13 x 18', 'false');
insert into format(name, is_deleted) values('16 x 10', 'false');
insert into format(name, is_deleted) values('17 x 11', 'false');
insert into format(name, is_deleted) values('18 x 11', 'false');
insert into format(name, is_deleted) values('20 x 14', 'false');
insert into format(name, is_deleted) values('21 x 15', 'false');
insert into format(name, is_deleted) values('22 x 17', 'false');
insert into format(name, is_deleted) values('24 x 17', 'false');
insert into format(name, is_deleted) values('25 x 19', 'false');
insert into format(name, is_deleted) values('29 x 20', 'false');
insert into format(name, is_deleted) values('36 x 27', 'false');
insert into format(name, is_deleted) values('А4', 'false');
insert into format(name, is_deleted) values('А5', 'false');
insert into format(name, is_deleted) values('А6', 'false');
insert into format(name, is_deleted) values('А7', 'false');